### ISSUE TITLE
无法下载多视频和图频混合微博的数据

### ISSUE THREAD

**Issue by pin189** [Coldmooon/weibo-image-crawler#1]
你好。经测试有以下两种类型的微博无法下载。
x 多个视频 https://weibo.com/6382231716/NvG3IoMbG
x 图频混合 https://weibo.com/6382231716/NxGoNtJ38
√多个图片 https://weibo.com/6382231716/Nzh2putCv
√单个视频 https://weibo.com/6382231716/NxRZJjEHU
![多个视频](https://github.com/Coldmooon/weibo-image-crawler/assets/79697022/c1fbea41-6558-4113-9f11-6b174f8e2231)
![图频混合](https://github.com/Coldmooon/weibo-image-crawler/assets/79697022/d9e34756-6de2-46b5-a130-8eac8abe7193)

**Comment by cookyecat** [comment]
谢谢！这份反馈非常有价值，我研究一下看看怎么解决

**Comment by cookyecat** [comment]
@pin189 问题已解决。

**Comment by pin189** [comment]
@Coldmooon 感谢。

**Comment by cookyecat** [comment]
@pin189 不客气，欢迎多提意见~！
